name: test-acrlogin
env:
  IMAGE_NAME: acrlogintest
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      acr_uri:
        type: string
        description: "ACR name"
        default: "acrname.azurecr.io"
      client_id:
        type: string
        description: "Client ID (in case of multiple managed identity)"
        default: ""
      tenant_id:
        type: string
        description: "tenant id"
        default: ""
jobs:
  hello_world_job:
    runs-on: self-hosted
    name: ACR Login job with managed identity
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: ACR login
        id: acrlogin
        uses: yaronpri/runner-acr-login-action@main
        with:
          acr_uri: ${{ github.event.inputs.acr_uri }}
          client_id: ${{ github.event.inputs.client_id }}
          tenant_id: ${{ github.event.inputs.tenant_id }}      
      - name: Docker build
        run: docker build -t ${{ github.event.inputs.acr_uri }}/${{ env.IMAGE_NAME}}:${{ github.sha }} .
      - name: Docker push
        run: docker push ${{ github.event.inputs.acr_uri }}/${{ env.IMAGE_NAME}}:${{ github.sha }}
  hello_world_comp:
    runs-on: ubuntu-latest
    name: A job to say hello from comp
    steps:
      - name: Hello world action step
        id: foo
        uses: yaronpri/hello-world-composite-action@main
        with:
          who-to-greet: ${{ inputs.acr_uri }}
      # Use the output from the `hello` step
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash