name: test-custom
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      acr_uri:
        type: string
        description: "ACR name"
        default: "acrname.azurecr.io"
      client_id:
        type: string
        description: "Client ID (in case of multiple managed identity)"
        default: ""
      tenant_id:
        type: string
        description: "tenant id"
        default: ""
jobs:
  hello_world_job:
    runs-on: self-hosted
    name: ACR Login job with managed identity
    steps:
      - name: ACR login
        id: acrlogin
        uses: yaronpri/hello-world-docker-action@main
        with:
          acr_uri: ${{ inputs.acr_uri }}
          client_id: ${{ inputs.client_id }}
          tenant_id: ${{ inputs.tenant_id }}
      # Use the output from the `hello` step
      #- name: Get the output time
      #  run: echo "The time was ${{ steps.acrlogin.outputs.time }}"
  hello_world_comp:
    runs-on: ubuntu-latest
    name: A job to say hello from comp
    steps:
      - name: Hello world action step
        id: foo
        uses: yaronpri/hello-world-composite-action@main
        with:
          who-to-greet: ${{ inputs.instring }}
      # Use the output from the `hello` step
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash