name: test-custom
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      acr:
        type: string
        description: "ACR name"
        default: "acrname.azurecr.io"
      tenant:
        type: string
        description: "tenant id"
        default: "tenant id"
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: ACR login
        id: acrlogin
        uses: yaronpri/hello-world-docker-action@main
        with:
          acr-uri: ${{ inputs.acr }}
          tenant-id: ${{ inputs.tenant }}
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.acrlogin.outputs.time }}"
  hello_world_comp:
    runs-on: ubuntu-latest
    name: A job to say hello from comp
    steps:
      - name: Hello world action step
        id: foo
        uses: yaronpri/hello-world-composite-action@main
        with:
          who-to-greet: ${{ inputs.instring }}
      # Use the output from the `hello` step
      - run: echo random-number ${{ steps.foo.outputs.random-number }}
        shell: bash